version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 # Contraseña para el usuario root
      MYSQL_DATABASE: evento-fotos # Base de datos inicial
    ports:
      - "3315:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
